### ISSUE TITLE
File and pay button does not get enabled for correction filing.

### ISSUE THREAD

**Issue by riyazuddinsyed** [bcgov/lear#1020]
**Describe the bug in current situation**
When the staff lands on the correction filing and fill all the mandatory fields and when he enters the payment info then the file and pay button is not enabled thereby blocking the filing

**Impact of this bug**
All staff users in dev 

**Steps to Reproduce**
1. Go to '.https://dev.bcregistry.ca/cooperatives/'
2. Click on Correction
3. File the Correction

**Actual/ observed behavior/ results**

**Expected behavior**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by seeker25** [comment]
Oldie, closing @riyazuddinsyed
