### ISSUE TITLE
Bugs in the PDF page

### ISSUE THREAD

**Issue by riyazuddinsyed** [bcgov/lear#262]
**Describe the bug**
The downloaded PDF contains all the information of the directors even though the stanaldone change of director's display section shows the expected output.

**To Reproduce**
1. Go to 'https://coops-dev.pathfinder.gov.bc.ca/Dashboard'
2. Click on 'Login' make changes in the Directors section both in standalone or AR then print the receipt then you see the error

**Expected behavior**
The downloaded PDF should only contains the current and newly appointed directors and should not display the ceased directors

GO with the CP0001364 && Passcode:238276299
 Now CEASE A DIRECTOR make the payment.
Then go the the PDF DOWNLOADS and then we get too see the ceased directors as well.

**Comment by katiemcgoff** [comment]
Resolved a while ago, but ticket not managed because in lear repo instead of entity.
