### ISSUE TITLE
PDF Outputs - all non-receipts fail to download

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/lear#270]
**Describe the bug**
In the Test environment, filings are completing, but the PDFs can't be downloaded from the dashboard.
The receipt works, but all others fail.

The only error, is a 500 on the following call:
GET https://legal-api-test.pathfinder.gov.bc.ca/api/v1/businesses/CP0001327/filings/173
Response:
{"message":"b'{\"message\": \"Internal Server Error\"}\\n'"}

Examples:
CP0001202, 922656210
CP0001327, 646253112

**To Reproduce**
1. Complete a filing
2. Once you're back on the dashboard, click a PDF
3. See error

**Comment by thorwolpert** [comment]
Please open in the Entities Repo if this is still an issue.
