### ISSUE TITLE
Stats for Filings

### ISSUE THREAD

**Issue by stevenc987** [bcgov/lear#651]
Would you mind helping me get some stats needed to measure the percent and rate of user adoption? I’m looking for:
-	Cooperative name
-	Cooperative number
-	Count of total filings completed per cooperative 
-	Display filing type completed for each cooperative.
-	I’m assuming all cooperatives that have completed filings are still active but if not, please check both historical and active states.

**Comment by thorwolpert** [comment]
Open this in the entities board.
